#image: http://my-docker-registry/my-docker-image:version
image: icecreammatt/lookup
script:
    - ./.drone/build.sh
    - ./.drone/stop_docker.sh
#    - go build
#    - go test
deploy:
    bash:
        script:
            - chmod 700 .drone/deploy.sh
            - ./drone/deploy.sh
#notify:
#  email:
#    recipients:
#      - email@example.com
